### ISSUE TITLE
[WIP] discussion around rework-again branch

### ISSUE THREAD

**Issue by eneiluj** [nextcloud/maps#39]
Hey how,

@tacruc and @eneiluj have been working and will probably continue on `rework-again` branch initially forked from `rework`. We agreed to make PRs to this branch from explicitly named and one-feature focused branches.

For example, I'm currently working on `eneiluj-tracks` and made a PR (#38) to `rework-again` where it can be discussed.

Here is a sort of milestone to reach before the first release candidate :nerd_face: : 

* [X] simple favorites management (#32)
* [X] simple photos display/placement (#32)
* [X] simple contacts display/placement (#34)
* [ ] calendar events
* [X] simple routing
* [X] simple tracks display (#38)
* [ ] simple devices locations get/display (#43)
* [x] ability to search in all layers (completion in search input etc...)
* [X] time based filtering system (with a double slider)
* [ ] guess photo positions with currently loaded tracks and devices information

Details to take care of:

* how/when do we set filtering slider values
* file hooks are to be reviewed
* in mobile view, swiping map to the right brings out the navigation menu
* contact of address book shared to me can be edited (placed) even if it's readonly

**Comment by tacruc** [comment]
Should we display calendar events on the map?

**Comment by eneiluj** [comment]
Yes why not. I forgot they can have an associated address.

**Comment by eneiluj** [comment]
I added some issues i found and didn't solve in the issue description.

**Comment by e-alfred** [comment]
This sounds awesome! Which routing engine do you intend to use? I once proposed OSRM to @v1r0x but anything that won't break after a short time would be great.

**Comment by eneiluj** [comment]
This is a big question, bigger than the tile provider (lots of public are available).

Actually I didn't find a public routing engine service using a compatible system (OSRM, Graphhopper, Mapbox Directions, Mapzen Valhalla, TomTom Online Routing, Esri). They all require an API key which, I suppose, is restricted to a domain name so we couldn't use it in every Nextcloud instance...

For the moment, the default OSRM is used but it's not always available and may sometimes have a strange behaviour.

We need to find a viable solution for routing.

**Comment by e-alfred** [comment]
Yeah, this is definitely a nuisance but for example the Weather app also requires an API key (from OpenWeatherMap) which works pretty well actually. It is a one-time setup anyway but the provider should be selected carefully (or, at least easily to migrate if one provider shuts down). Maybe Openrouteservice (https://openrouteservice.org/) could be an alternative too?

**Comment by eneiluj** [comment]
OpenRouteService is not an option for the moment. Check out the leaflet plugin I chose: http://www.liedman.net/leaflet-routing-machine/ . There's a list of compatible routing engines.

This plugin is extensible and could be made compatible with OpenRouteService.

One thing is sure: We can't ask each Nextcloud admin to register to get a routing service API key.

**Comment by jancborchardt** [comment]
I’d say that’s already a lot of features for a first release. :) We can use this issue for more overarching feature discussion, I commented with design reviews at the pull request instead: https://github.com/nextcloud/maps/pull/44

**Comment by jancborchardt** [comment]
> One thing is sure: We can't ask each Nextcloud admin to register to get a routing service API key.

Yup. So we can just go with the default as it is now, and in the future think about offering a config setting where admins could add their specific routing service API key if they rely on the Maps app. That makes it work for all basic setups, and scales up if people use it more.

**Comment by e-alfred** [comment]
Currently this is shown in the browser console:

```
You are using OSRM's demo server. Please note that it is **NOT SUITABLE FOR PRODUCTION USE**.
Refer to the demo server's usage policy: https://github.com/Project-OSRM/osrm-backend/wiki/Api-usage-policy

To change, set the serviceUrl option.

Please do not report issues with this server to neither Leaflet Routing Machine or OSRM - it's for
demo only, and will sometimes not be available, or work in unexpected ways.

Please set up your own OSRM server, or use a paid service provider for production.
```

So it would be a good idea to let the admin/user set their own tile server or API key and warn them that the default setting is for demonstration purposes only.

**Comment by jancborchardt** [comment]
I’d say let’s close this issue as it has a lot of different aspects in it and a lot of it is already implemented. We should open separate issues for each different feature or issue. :)
