### ISSUE TITLE
ToDo non localized pictures

### ISSUE THREAD

**Issue by tacruc** [nextcloud/maps#45]
### Backend

- [ ] Different gpx loading to allow for big gpx files as coming from google timeline.
- [ ] do the matching smarter.
- [ ] Cache TimeordedPointSets for x seconds
- [ ] Change API for lazy loading
- [x] Read Point from gpx wptType, rteType, ~~trkType which are not in a trkseg (allready done)~~

### Frontend
- [ ] lazy load nonlocalizedPhots
- [ ] restructure  Photo menu entry, plug bot photos in one main menu entry

**Comment by eneiluj** [comment]
> lazy load nonlocalizedPhotos

What do you mean by that? They already are lazy loaded when needed. Could you more precise?

About photos, @jancborchardt said there shouldn't be any difference between localized and non-localized photos in terms of interface. I don't have a strong opinion about that. I would say it's nice to at least make the popup have a different color (like warning color currently used).

About the menu entries, I think I agree with @jancborchardt it would be nicer to have just one named Photos which would show localized AND non-localized photos.

**Comment by tacruc** [comment]
> > lazy load nonlocalizedPhotos
> 
> What do you mean by that? They already are lazy loaded when needed. Could you more precise?

I mean the loading of the marker location, not of the image. 

1. A request where the list of nonlocalized Id's is loaded.
2. One request resolving the set of (lat, lng) pair for each photo.


```

About photos, @jancborchardt said there shouldn't be any difference between localized and non-localized photos in terms of interface. I don't have a strong opinion about that. I would say it's nice to at least make the popup have a different color (like warning color currently used).

About the menu entries, I think I agree with @jancborchardt it would be nicer to have just one named Photos which would show localized AND non-localized photos.
```

I think this is similar to option A, because the sub entries would be toggled as default anyways. I don't have a strong opinion if they should exist or not. But if it doesn't exists we shouldn't show the pictures without guess at the current position, or what do you thin?

**Comment by jancborchardt** [comment]
> About photos, @jancborchardt said there shouldn't be any difference between localized and non-localized photos in terms of interface. I don't have a strong opinion about that. I would say it's nice to at least make the popup have a different color (like warning color currently used).

What we could do is in the second row (where the filename is shown) just put (estimated location) in parentheses like so:

> **Tuesday, 19 July 2017, 20:34**
> IMG_09448.jpg (estimated location)

What do you think?


> About the menu entries, I think I agree with @jancborchardt it would be nicer to have just one named Photos which would show localized AND non-localized photos.

Yes, I think that’s quite important, as otherwise you have this default entry which actually looks like an error or some strange thing. We should just go with the estimation and do it. (OR not show the non-localized ones at all. But a strange inbetween is a bit off.)

**Comment by tacruc** [comment]
@eneiluj do you think loading gpx wptType, rteType point make sence? I added the todo but now I'm not shure if it makes sence.

**Comment by eneiluj** [comment]
@tacruc No it probably does not make sense indeed. Waypoints are most likely added manually so they don't refer to a potential photo position.

**Comment by e-alfred** [comment]
One problem I see with loads of non-localized pictures is that they are loaded all at the same place and it takes really long if they are in the thousands. Also, so many pictures in one place are very hard to navigate so there should be some loading mechanism to limit the number of pictures loaded at once.

**Comment by e-alfred** [comment]
One problem I see with loads of non-localized pictures is that they are loaded all at the same place and it takes really long if they are in the thousands. Also, so many pictures in one place are very hard to navigate so there should be some loading mechanism to limit the number of pictures loaded at once.

The occ:scan-photos shows no output even in verbose mode but the scan works and the database table is filled up. This is probably a bug.

**Comment by tacruc** [comment]
- The long loading is addressed, with the new PR. 

- If you have Tracks or devices loaded. The pictures are placed along the track/device history.  So only pictures, where no track/ device history is available, when they where taken are placed at your current position. There are three options what to do about those pictures.
  - I'm still thinking about not showing those picture without a guess or 
  - limiting them to some number x. 
  - But on the other hand you still have the time filter to Filter to a specific range.

**Comment by tacruc** [comment]
>     * The long loading is addressed, with the new PR #46.

This doesn't improve anything, if a huge gpx file is imported. For testing I imported the google timeline with 165mb. I will have to reconsider it.

**Comment by tacruc** [comment]
I will close this for now. For reasonable number of pictures the code is fast and for big collection it is the best I cloud get.
